export const Images = {
  background: require('./background.png'),
  headerLogo: require('./headerLogo.png'),
  headerTitle: require('./headerTitle.png'),
  logo: require('./logo.png'),
  appleStore: require('./appleStore.png'),
  googlePlay: require('./googlePlay.png'),
  apkQrCode: require('./apkQrCode.png'),
  googleQrCode: require('./googleQrCode.png'),
  appleQrCode: require('./appleQrCode.png'),
  bcoinWhiteIcon: require('./bcoinWhiteIcon.png'),
  bcoinBlueIcon: require('./bcoinBlueIcon.png'),
  tickIcon: require('./tickIcon.png'),
  heartFilled: require('./heartFilled.png'),
  heartOutlined: require('./heartOutlined.png'),
  chatIcon: require('./chatIcon.png'),
  defaultAvatar: require('./defaultAvatar.png'),
  avatarBwell: require('./avatarBwell.png'),
  notificationIcon: require('./notificationIcon.png'),
  notificationSelectedIcon: require('./notificationSelectedIcon.png'),
  settingIcon: require('./settingIcon.png'),
  settingSelectedIcon: require('./settingSelectedIcon.png'),
  profileIcon: require('./profileIcon.png'),
  cameraIcon: require('./camera.png'),
  rightArrow: require('./rightArrow.png'),
  rightArrowBlue: require('./rightArrowBlue.png'),
  teamIconBlue: require('./teamIconBlue.png'),
  teamIconWhite: require('./teamIconWhite.png'),
  teamLeaderIcon: require('./teamLeaderIcon.png'),
  teamLeaderIconBlue: require('./teamLeaderIconBlue.png'),
  teamMemberIcon: require('./teamMemberIcon.png'),
  memberIcon: require('./memberIcon.png'),
  infoIcon: require('./infoIcon.png'),
  jumpToRankIcon: require('./jumpToRankIcon.png'),
  viewRecordingIcon: require('./viewRecordingIcon.png'),
  aboutLTG: require('./aboutLTG.png'),
  camera: require('./camera.png'),
  editIcon: require('./editIcon.png'),
  signature: require('./signature.png'),
  tutorial1: require('./tutorial1.png'),
  tutorial2: require('./tutorial2.png'),
  tutorial3: require('./tutorial3.png'),
  tutorial4: require('./tutorial4.png'),
  rightArrowBordered: require('./rightArrowBordered.png'),
  leftArrowBordered: require('./leftArrowBordered.png'),
  deleteIcon: require('./deleteIcon.png'),
  deleteWhiteIcon: require('./deleteWhiteIcon.png'),
  flagIcon: require('./flagIcon.png'),
  lockIcon: require('./lockIcon.png'),
  lockIconGrey: require('./lockIconGrey.png'),
  unlockIcon: require('./unlockIcon.png'),
  unlockIconGreen: require('./unlockIconGreen.png'),
  scrollTopIcon: require('./scrollTopIcon.png'),
  barclayHeadPhoto: require('./barclayHeadPhoto.png'),
  searchIcon: require('./searchIcon.png'),
  calendarIcon: require('./calendarIcon.png'),
  searchIconAlt: require('./searchIconAlt.png'),
  closeIcon: require('./closeIcon.png'),

  fitness: {
    stravaButton: require('./fitness/stravaButton.png'),
    appleButton: require('./fitness/appleButton.png'),
    googleButton: require('./fitness/googleButton.png'),
    fitbitButton: require('./fitness/fitbitButton.png'),
  },
  navigation: {
    rankingIcon: require('./navigation/rankingIcon.png'),
    activityIcon: require('./navigation/activityIcon.png'),
    clubIcon: require('./navigation/clubIcon.png'),
    challengeIcon: require('./navigation/challengeIcon.png'),
    liveIcon: require('./navigation/liveIcon.png'),
    meetupIcon: require('./navigation/meetupIcon.png'),
    charityIcon: require('./navigation/charityIcon.png'),
  },
  clubActivities: {
    arts_crafts: require('./clubActivities/arts_crafts.png'),
    cycling: require('./clubActivities/cycling.png'),
    entertainment: require('./clubActivities/entertainment.png'),
    fitness_strength: require('./clubActivities/fitness_strength.png'),
    hiking_walking: require('./clubActivities/hiking_walking.png'),
    mental_wellbeing: require('./clubActivities/mental_wellbeing.png'),
    personal_development: require('./clubActivities/personal_development.png'),
    philanthropy: require('./clubActivities/philanthropy.png'),
    running: require('./clubActivities/running.png'),
    sustainability: require('./clubActivities/sustainability.png'),
    travel_food_wine: require('./clubActivities/travel_food_wine.png'),
    yoga_pilates: require('./clubActivities/yoga_pilates.png'),
  },
  clubRank: {
    bronze: require('./clubRank/rank_bronze.png'),
    silver: require('./clubRank/rank_silver.png'),
    gold: require('./clubRank/rank_gold.png'),
    platinum: require('./clubRank/rank_platinum.png'),
    diamond: require('./clubRank/rank_diamond.png'),
    unrank: require('./clubRank/rank_unrank.png'),
    not_member: require('./clubRank/rank_not_member.png'),
  },
  country: {
    hongKong: require('./country/HongKong.png'),
    india: require('./country/India.png'),
    singapore: require('./country/Singapore.png'),
    china: require('./country/China.png'),
    australia: require('./country/Australia.png'),
    japan: require('./country/Japan.png'),
  },
  badges: [
    require('./badges/badge_bronze_1.png'),
    require('./badges/badge_bronze_2.png'),
    require('./badges/badge_bronze_3.png'),
    require('./badges/badge_silver_1.png'),
    require('./badges/badge_silver_2.png'),
    require('./badges/badge_silver_3.png'),
    require('./badges/badge_gold_1.png'),
    require('./badges/badge_gold_2.png'),
    require('./badges/badge_gold_3.png'),
    require('./badges/badge_platinum_1.png'),
    require('./badges/badge_platinum_2.png'),
    require('./badges/badge_platinum_3.png'),
    require('./badges/badge_diamond_1.png'),
    require('./badges/badge_diamond_2.png'),
    require('./badges/badge_diamond_3.png'),
  ],

  notfound: require('./notfoundpage.svg'),
};
